facebook:
  client:
    clientId: 2353087608084891
    clientSecret: 851b6000625a49b7242bba5138fd659a
    accessTokenUri: https://graph.facebook.com/v3.3/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/v3.3/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: public_profile email
    registered-redirect-uri: https://adnane-shop.herokuapp.com/login/facebook
    pre-established-redirect-uri: https://adnane-shop.herokuapp.com/login/facebook
    use-current-uri: false
  resource:
    userInfoUri: https://graph.facebook.com/me?fields=email,name
google:
  client:
    clientId: 1057156416076-htj4lmc9tu481ie744sjbhef785rdthp.apps.googleusercontent.com
    clientSecret: d0rMY7d7ck2Pjd_cHash4O5J
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
    scope: profile email
  resource:
    userInfoUri: https://www.googleapis.com/userinfo/v2/me
    preferTokenInfo: false